"""init models

Revision ID: f14aa3bcd565
Revises: 
Create Date: 2026-06-20 20:47:43.783640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14aa3bcd565'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_officers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('county', sa.String(length=80), nullable=False),
    sa.Column('sub_county', sa.String(length=80), nullable=True),
    sa.Column('crops_json', sa.Text(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_link', sa.String(length=200), nullable=True),
    sa.Column('facebook_url', sa.String(length=300), nullable=True),
    sa.Column('instagram_url', sa.String(length=300), nullable=True),
    sa.Column('tiktok_url', sa.String(length=300), nullable=True),
    sa.Column('twitter_url', sa.String(length=300), nullable=True),
    sa.Column('website_url', sa.String(length=300), nullable=True),
    sa.Column('tier', sa.Enum('free', 'basic', 'pro', name='officertier'), nullable=False),
    sa.Column('subscription_expires', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('contact_clicks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_officers_county'), 'extension_officers', ['county'], unique=False)
    op.create_index(op.f('ix_extension_officers_email'), 'extension_officers', ['email'], unique=True)
    op.create_index(op.f('ix_extension_officers_specialization'), 'extension_officers', ['specialization'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('county', sa.String(length=80), nullable=True),
    sa.Column('sub_county', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('primary_crop', sa.String(length=120), nullable=True),
    sa.Column('farm_size_acres', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_county'), 'farmers', ['county'], unique=False)
    op.create_index(op.f('ix_farmers_device_id'), 'farmers', ['device_id'], unique=True)
    op.create_index(op.f('ix_farmers_primary_crop'), 'farmers', ['primary_crop'], unique=False)
    op.create_table('input_ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_kes', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('target_categories_json', sa.Text(), nullable=True),
    sa.Column('target_crops_json', sa.Text(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_link', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listing_expires', sa.Date(), nullable=True),
    sa.Column('impression_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_domain', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('last_modified', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'rejected', 'error', name='contentstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_raw_content_url')
    )
    op.create_index(op.f('ix_raw_content_source_domain'), 'raw_content', ['source_domain'], unique=False)
    op.create_index(op.f('ix_raw_content_status'), 'raw_content', ['status'], unique=False)
    op.create_index(op.f('ix_raw_content_url'), 'raw_content', ['url'], unique=False)
    op.create_table('solution_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('card_kind', sa.Enum('problem', 'practice', 'advisory', 'input', name='cardkind'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_schema_version', sa.Integer(), nullable=False),
    sa.Column('extra_notes', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.Enum('pest', 'disease', 'soil', 'livestock', 'weather', 'input', 'harvest', name='cardcategory'), nullable=False),
    sa.Column('crop', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ai_model_version', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_content_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'review', 'archived', name='cardstatus'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_content_id'], ['raw_content.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_cards_card_kind'), 'solution_cards', ['card_kind'], unique=False)
    op.create_index(op.f('ix_solution_cards_category'), 'solution_cards', ['category'], unique=False)
    op.create_index(op.f('ix_solution_cards_crop'), 'solution_cards', ['crop'], unique=False)
    op.create_index(op.f('ix_solution_cards_region'), 'solution_cards', ['region'], unique=False)
    op.create_index(op.f('ix_solution_cards_status'), 'solution_cards', ['status'], unique=False)
    op.create_index(op.f('ix_solution_cards_title'), 'solution_cards', ['title'], unique=False)
    op.create_table('card_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('county', sa.String(length=80), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['solution_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_views_card_id'), 'card_views', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_views_county'), 'card_views', ['county'], unique=False)
    op.create_index(op.f('ix_card_views_device_id'), 'card_views', ['device_id'], unique=False)
    op.create_index(op.f('ix_card_views_viewed_at'), 'card_views', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_views_viewed_at'), table_name='card_views')
    op.drop_index(op.f('ix_card_views_device_id'), table_name='card_views')
    op.drop_index(op.f('ix_card_views_county'), table_name='card_views')
    op.drop_index(op.f('ix_card_views_card_id'), table_name='card_views')
    op.drop_table('card_views')
    op.drop_index(op.f('ix_solution_cards_title'), table_name='solution_cards')
    op.drop_index(op.f('ix_solution_cards_status'), table_name='solution_cards')
    op.drop_index(op.f('ix_solution_cards_region'), table_name='solution_cards')
    op.drop_index(op.f('ix_solution_cards_crop'), table_name='solution_cards')
    op.drop_index(op.f('ix_solution_cards_category'), table_name='solution_cards')
    op.drop_index(op.f('ix_solution_cards_card_kind'), table_name='solution_cards')
    op.drop_table('solution_cards')
    op.drop_index(op.f('ix_raw_content_url'), table_name='raw_content')
    op.drop_index(op.f('ix_raw_content_status'), table_name='raw_content')
    op.drop_index(op.f('ix_raw_content_source_domain'), table_name='raw_content')
    op.drop_table('raw_content')
    op.drop_table('input_ads')
    op.drop_index(op.f('ix_farmers_primary_crop'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_device_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_county'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_extension_officers_specialization'), table_name='extension_officers')
    op.drop_index(op.f('ix_extension_officers_email'), table_name='extension_officers')
    op.drop_index(op.f('ix_extension_officers_county'), table_name='extension_officers')
    op.drop_table('extension_officers')
    # ### end Alembic commands ###
